name: Publish Node Docker
on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "nath4nn" --password-stdin
        docker image build -t nath4nn/egco341_docker2:latest .
        docker push nath4nn/egco341_docker2:latest
